name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Create config
        run: mv config_example.yaml config.yaml

      - name: Make in and out directories
        run: mkdir in out test_data/out

      - name: Run build
        run: cargo build --verbose
        
      - name: Run tests
        run: cargo test --verbose
